version: '3.8' # Versión de Docker Compose

services:
  # 1. Servicio de Base de Datos: MySQL
  db:
    image: mysql:8.0 # Utiliza la imagen oficial de MySQL 8.0
    container_name: mysql-dev-bbdd
    # Reinicia automáticamente si falla o se detiene
    restart: always 
    environment:
      # Variables esenciales para la configuración inicial de MySQL
      MYSQL_ROOT_PASSWORD: rootpassword # ¡IMPORTANTE! Cambiar en producción
      MYSQL_DATABASE: mi_bbdd_dev
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
    volumes:
      # Mapea un volumen persistente para guardar los datos de la BBDD
      - db_data:/var/lib/mysql 
      # Mapea un archivo SQL para inicializar la BBDD (Opcional)
      # - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      # Mapea el puerto 3306 del contenedor al puerto 3306 de tu máquina
      - "3306:3306" 

  # 2. Servicio de Gestión de Base de Datos: phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-dev-gui
    restart: always
    environment:
      # Configuración para conectar a nuestro servicio 'db' (MySQL)
      PMA_HOST: db 
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword # Usa la misma contraseña ROOT que MySQL
    ports:
      # Mapea el puerto 80 del contenedor al puerto 8082 de tu máquina, si ya está siendo usado utiliza otro puerto diferente
      - "8082:80" 
    depends_on:
      - db # Asegura que el servicio 'db' se inicie antes que phpMyAdmin

# Definición de volúmenes persistentes
volumes:
  db_data: