version: '3.8'

services:
  # Servidor Backend (simula el punto de despliegue)
  backend:
    image: node:18-alpine
    container_name: web_backend_ci
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "3000:3000"
    # Comando de ejecución del backend
    command: ["node", "server.js"]
    networks:
      - web-network

  # Servidor Frontend/Dev (simula entorno de desarrollo)
  frontend-dev:
    image: nginx:stable-alpine
    container_name: web_frontend_dev
    # Montamos la carpeta del frontend en la ruta de Nginx
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - web-network
    # Garantiza que el servidor Nginx esté levantado
    command: ["nginx", "-g", "daemon off;"]

networks:
  web-network:
    driver: bridge